# apiVersion: v1
# kind: Service
# metadata:
#   name: tomato-nodeport
#   namespace: default
#   labels:
#     app: tomato
# spec:
#   type: NodePort
#   selector:
#       app: tomato
#   ports:
#   - port: 4000
#     targetPort: 80
#     nodePort: 30000