apiVersion: v1
kind: Service
metadata:
  name: tomato-clusterip-service
  labels:
    app: tomato
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: tomato
  ports:
  - port: 80
    targetPort: 80