apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-tomato-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tusharupase258/Github_Actions_AKS_End_2_End.git
    targetRevision: main
    path: Tushar-s-Tomato/helm_chart/tomatohelm/
    helm:
      valueFiles:
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true