name: Build & Push streamflix

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_name:
        description: "Enter Docker Image Name"
        required: true
        default: "streamflix"
      image_tag:
        description: "Enter Image Tag"
        required: true
        default: "latest"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Image Name & Tag
        run: |
          IMAGE_NAME=${{ github.event.inputs.image_name || 'streamflix' }}
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"

      - name: Azure Login (Service Principal)
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f StreamFlix/dockerfile StreamFlix

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
